name: Node.js CI

on:
  workflow_dispatch: # manual trigger
  push:             # run on push too (optional)
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Start the bot
        env:
          PORT: 3000   # ✅ non-privileged port
        run: |
          echo "🚀 Starting bot..."
          nohup npm start > bot.log 2>&1 &   # run in background
          sleep 10
          tail -f bot.log                    # keep job alive + show logs
